debug = true
timeout = 5
[redis]
    address = "127.0.0.1:6379"
    auth = "alonexy"
    type = "tcp"

[tcp]
    bind = ":9991"
    timeout = 10

[websocket]
    bind = ":9090"
    tlsOpen = true
    tlsBind = ":9091"
    certFile = "./files/1_.crt"
    privateFile = "./files/2_.key"

[auth]
    username = "alonexy"
    passwd = "123456"